# Generated by Django 3.1.2 on 2020-10-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201015_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(),
        ),
    ]
